[project]
name = "opencv"
version = "0.1.0"
description = "Opencv examples"
authors = ["Ruben Arts <ruben@prefix.dev>"]
channels = ["conda-forge"]
platforms = ["linux-64", "win-64", "osx-64", "osx-arm64"]

[tasks]
start = "python webcam_capture.py"
calibrate = "python calibrate.py"

[dependencies]
opencv = "*"
python = "3.10.*"
requests = "*"
autopep8 = "2.0.4.*"
flake8 = "6.1.0.*"
